name: "Style check"
description: "Style check using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the variable
        PROJECT_PATH=$(pwd)

        echo $PROJECT_PATH

        # Busca en los directorios /src, /lib y /include todos los archivos .c .cpp. hpp y .h que haya y los lista, luego
        # con el comando 'tr' reemplaza los saltos de línea '\n' por espacios ' ', quedando así los archivos concatenados en una sola línea.
        # El comando 'tr' sirve para transformar o eliminar caracteres específicos.
        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/lib -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        # Se ejecuta clang-format sobre los archivos mencionados arriba para formatearlos con las reglas definidas y que se 
        # modifiquen los archivos originales (opción -i). Luego si se produce un error, esta salida se redirige al archivo 'clang-format_errors.txt'
        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) > ${ERROR_FILE_FLAG}

        echo "Running: clang-format -i $SOURCE_FILES"

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Clang-format errors!!!
        path: $PROJECT_PATH/clang-format_errors.txt
        retention-days: 1
