name: "Doc check"
description: "Code documentation generation with Doxygen"

runs:
  using: "composite"
  steps:
    - name: "Run doxygen command"
      shell: bash
      run: |
          # We only make check, not changes
          DOX_CONF_FILE=$(pwd)/Doxyfile

          # Se especifican las carpetas de entrada para Doxygen, es decir, los lugares donde Doxygen buscará archivos para documentar.
          # luego se redirige toda la salida del grupo de comandos al archivo Doxyfile
          {
              cat $DOX_CONF_FILE
              echo "INPUT = $(pwd)/src $(pwd)/include $(pwd)/lib"
          } > $DOX_CONF_FILE

          # Generate documentation
          sudo dot -c

          ERROR_FILE_FLAG=$(pwd)/dox_errors.txt

          # Se ejecuta el comando de doxygen para que sólo realice una verificación de la configuración. Luego si hay algún error en la
          # ejecución del comando, se produce una salida con el mismo y esta se redirige al archivo 'dox_errors.txt'
          DOXYGEN_COMMAND=$(doxygen -s $DOX_CONF_FILE) > $ERROR_FILE_FLAG

          if [ -s $ERROR_FILE_FLAG ]; then
              echo "Error: There are some files that are not documented correctly"
              exit 1
          else
              echo "All files are documented correctly. Niiiceee"
              exit 0
          fi
    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Doxygen errors!!!
        path: $(pwd)/dox_errors.txt
        retention-days: 1
